// Code generated by construct, DO NOT EDIT.
package repository

import (
	uuid "github.com/gofrs/uuid"
	model "github.com/networkteam/construct/v2/example/pgx/model"
	qrb "github.com/networkteam/qrb"
	builder "github.com/networkteam/qrb/builder"
	fn "github.com/networkteam/qrb/fn"
)

var (
	project_id    = qrb.N("projects.id")
	project_title = qrb.N("projects.title")
)
var projectSortFields = map[string]builder.IdentExp{}

type ProjectChangeSet struct {
	ID    *uuid.UUID
	Title *string
}

func (c ProjectChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["id"] = *c.ID
	}
	if c.Title != nil {
		m["title"] = *c.Title
	}
	return m
}

func ProjectToChangeSet(r model.Project) (c ProjectChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	c.Title = &r.Title
	return
}

var projectDefaultJson = fn.JsonBuildObject().
	Prop("ID", project_id).
	Prop("Title", project_title)
