// Code generated by construct, DO NOT EDIT.
package repository

import (
	"database/sql"
	"encoding/json"
	uuid "github.com/gofrs/uuid"
	construct "github.com/networkteam/construct/v2"
	model "github.com/networkteam/construct/v2/example/pgx/model"
	cjson "github.com/networkteam/construct/v2/json"
)

const (
	project_id    = "projects.id"
	project_title = "projects.title"
)

var projectSortFields = map[string]string{}

type ProjectChangeSet struct {
	ID    *uuid.UUID
	Title *string
}

func (c ProjectChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["id"] = *c.ID
	}
	if c.Title != nil {
		m["title"] = *c.Title
	}
	return m
}

func ProjectToChangeSet(r model.Project) (c ProjectChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	c.Title = &r.Title
	return
}

var projectDefaultSelectJson = cjson.JsonBuildObject().
	Set("ID", cjson.Exp("projects.id")).
	Set("Title", cjson.Exp("projects.title"))

func projectScanJsonRow(row construct.RowScanner) (result model.Project, err error) {
	var data []byte
	if err := row.Scan(&data); err != nil {
		if err == sql.ErrNoRows {
			return result, construct.ErrNotFound
		}
		return result, err
	}
	return result, json.Unmarshal(data, &result)
}
